# Generated by Django 4.2.6 on 2023-11-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage_app', '0004_staff_rename_address_student_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
