# Generated by Django 4.2.6 on 2023-11-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage_app', '0006_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
