# Generated by Django 4.2.6 on 2023-11-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage_app', '0010_alter_subject_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
