# Generated by Django 4.2.6 on 2023-11-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage_app', '0012_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdmanage_app.staff')),
            ],
        ),
    ]
