# Generated by Django 4.2.6 on 2023-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage_app', '0013_staff_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notifications',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
