# Generated by Django 4.2.6 on 2023-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage_app', '0014_alter_staff_notifications_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notifications',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
