# Generated by Django 4.2.6 on 2023-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage_app', '0021_attendance_attendance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
